baseURL = "http://linj-disanbo.github.io/"
languageCode = "cn"
title = "linjing's blog"
theme = "m10c"


[params]
  description = "记录, 总结, 避免遗忘"
  avatar = "me.jpg"
  notoc = false

[[params.social]]
  name = "github"
  url = "https://github.com/linj-disanbo"

